### ISSUE TITLE
[HELP] Unsupported protocol: 'undefined' or protocol version: 'undefined'

### ISSUE THREAD

**Issue by MoustafaMohsen** [SAP/e-mobility-charging-stations-simulator#1021]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Component

Simulator

### Description

- Simulator console output 
```
error: 3/28/2024, 6:01:22 AM UI WebSocket Server | Unsupported protocol: 'undefined' or protocol version: 'undefined'
error: 3/28/2024, 6:01:22 AM UI WebSocket Server | UIWebSocketServer.start.server.onconnection: Unsupported UI protocol version: ''
debug: 3/28/2024, 6:01:22 AM UI WebSocket Server | UIWebSocketServer.start.ws.onclose: WebSocket closed: 'Abnormal Closure' - ''
error: 3/28/2024, 6:01:22 AM CS-SIEMENS | WebSocket error: Server sent no subprotocol {"stack":"Error: Server sent no subprotocol\n    at ClientRequest.<anonymous> (/Users/moustafa/Projects/Personal/Tech/Gitlab/ocpp-simulators/e-mobility-charging-stations-simulator/node_modules/.pnpm/ws@8.16.0_bufferutil@4.0.8_utf-8-validate@6.0.3/node_modules/ws/lib/websocket.js:959:7)\n    at ClientRequest.emit (node:events:518:28)\n    at Socket.socketOnData (node:_http_client:575:11)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)\n    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)"}
error: 3/28/2024, 6:01:22 AM CS-SIEMENS | WebSocket abnormally closed with status 'Abnormal Closure' and reason ''
error: 3/28/2024, 6:01:22 AM CS-SIEMENS | WebSocket connection retry in 30000ms, timeout 29000ms
error: 3/28/2024, 6:01:52 AM CS-SIEMENS | WebSocket connection retry #1
```

### Version

1.3.1

### Node.js version

v20.11.1

### System

  System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 665.14 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh

### Expected result

Charging station is able to open ws connection

### Actual result

WebUI can see the charging station but cannot open the connection or send transactions.

### Steps to reproduce

- Copy `src/assets/config-template.json` to `src/assets/config.json`
- Copy `src/assets/idtags-template.json` to `src/assets/idtags.json`
- Set `src/assets/config.json`
```json
{
  "supervisionUrls": [
    "ws://localhost:8080/OCPP16/5be7fb271014d90008992f06"
  ],
  "supervisionUrlDistribution": "round-robin",
  "log": {
    "file": "logs/combined.log",
    "errorFile": "logs/error.log",
    "maxFiles": 7,
    "statisticsInterval": 0,
    "level": "debug",
    "console": true
  },
  "worker": {
    "processType": "workerSet"
  },
  "performanceStorage": {
    "enabled": true,
    "type": "none"
  },
  "uiServer": {
    "enabled": true,
    "type": "ws",
    "authentication": {
      "enabled": false,
      "type": "basic-auth",
      "username": "admin",
      "password": "admin"
    }
  },
  "stationTemplateUrls": [
    {
      "file": "siemens.station-template.json",
      "numberOfStations": 1
    }
  ]
}
```
- execute `pnpm start:dev:debug`
- in a new terminal cd to `cd ui/web`
- set `ui/web/public/config.json`
```json
{
  "uiServer": {
    "host": "localhost",
    "port": 8080,
    "protocol": "ui",
    "version": "0.0.1",
    "authentication": {
      "enabled": false,
      "type": "",
      "username": "",
      "password": ""
    }
  }
}
```
- run web UI `pnpm dev`

### Attachments

- simulator console log
![Screenshot 2024-03-28 at 6 15 55 AM](https://github.com/SAP/e-mobility-charging-stations-simulator/assets/32576530/00786828-a048-4d71-a029-5bcd119e8ce1)

- web ui
![Screenshot 2024-03-28 at 6 43 31 AM](https://github.com/SAP/e-mobility-charging-stations-simulator/assets/32576530/1902a0a0-43b5-4fb5-850f-acbd0b9d10ea)

I have read the documentation thoroughly but I suspect I might be missing something in the configurations, can someone help me ?

**Comment by jerome-benoit** [comment]
The authentication configuration is incorrect and does not match the documentation.
The notice at issue creation is crystal clear: issues are meant for bug, not end-user support => closing.
