### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by anishagrwl** [SAP/e-mobility-charging-stations-simulator#1036]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Component

Simulator

### Description

[Cannot send command StatusNotification PDU when the charging station is in undefined state on the central server](error: 4/28/2024, 9:56:31 PM CS-SCHNEIDER-00001 | Request command 'StatusNotification' error: Cannot send command StatusNotification PDU when the charging station is in undefined state on the central server {"code":"SecurityError","command":"StatusNotification","date":"2024-04-28T16:11:31.960Z","name":"T","stack":"T: Cannot send command StatusNotification PDU when the charging station is in undefined state on the central server\n    at Ir.internalSendMessage (file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:6:63975)\n    at Ir.sendMessage (file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:6:60697)\n    at Ir.requestHandler (file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:6:66321)\n    at Pe (file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:6:14208)\n    at n.stopMessageSequence (file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:7:30748)\n    at async n.stop (file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:7:2706)\n    at async file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:6:97543\n    at async An.commandHandler (file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:6:101234)"})

### Version

1.3.2

### Node.js version

18.18.0

### System

Cannot send command StatusNotification PDU when the charging station is in undefined state on the central server](error: 4/28/2024, 9:56:31 PM CS-SCHNEIDER-00001 | 

### Expected result

Able to connect to charging station

### Actual result

NA

### Steps to reproduce

NA

### Attachments

error: 4/28/2024, 9:56:31 PM CS-SCHNEIDER-00001 | Request command 'StatusNotification' error: Cannot send command StatusNotification PDU when the charging station is in undefined state on the central server {"code":"SecurityError","command":"StatusNotification","date":"2024-04-28T16:11:31.960Z","name":"T","stack":"T: Cannot send command StatusNotification PDU when the charging station is in undefined state on the central server\n    at Ir.internalSendMessage (file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:6:63975)\n    at Ir.sendMessage (file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:6:60697)\n    at Ir.requestHandler (file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:6:66321)\n    at Pe (file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:6:14208)\n    at n.stopMessageSequence (file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:7:30748)\n    at async n.stop (file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:7:2706)\n    at async file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:6:97543\n    at async An.commandHandler (file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:6:101234)"}
error: 4/28/2024, 10:00:29 PM CS-SCHNEIDER-00001 | Request command 'StatusNotification' error: Cannot send command StatusNotification PDU when the charging station is in undefined state on the central server {"code":"SecurityError","command":"StatusNotification","date":"2024-04-28T16:15:29.987Z","name":"T","stack":"T: Cannot send command StatusNotification PDU when the charging station is in undefined state on the central server\n    at Ir.internalSendMessage (file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:6:63975)\n    at Ir.sendMessage (file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:6:60697)\n    at Ir.requestHandler (file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:6:66321)\n    at Pe (file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:6:14208)\n    at n.stopMessageSequence (file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:7:30748)\n    at async n.stop (file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:7:2706)\n    at async file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:6:97543\n    at async An.commandHandler (file:///Users/anishagrawal/Desktop/OCPP_SImulator/clone/e-mobility-charging-stations-simulator/dist/ChargingStationWorker.js:6:101234)"}

**Comment by jerome-benoit** [comment]
@anishagrwl: the issue template clearly states that they are dedicated to bug report, not end user support request at simulator usage. We do not have the bandwidth to do end user support, nor to explain what is a client/server paradigm, nor how to make comprehensive bug report, nor how to read a GitHub issue template, etc.
