### ISSUE TITLE
[BUG] elementAddDelay should be elementStartDelay in the readme

### ISSUE THREAD

**Issue by bramley-jetcharge** [SAP/e-mobility-charging-stations-simulator#1055]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Component

Simulator

### Description

Just a minor one, but it was difficult to spot.
The readme documents worker startup config `elementAddDelay`, but the field is actually called `elementStartDelay`.

This field is useful to add a delay between each charger connecting, so I don't DoS my ocpp server :)

### Version

latest

### Node.js version

not relevant

### System

not relevant

**Comment by jerome-benoit** [comment]
I do not understand: the tunable was renamed to `elementAddDelay` with a deprecation warning on `elementStartDelay`. And the code properly handle `elementAddDelay` as `elementStartDelay`. 

What is actually not working with the `elementAddDelay` tunable?

**Comment by jerome-benoit** [comment]
Will be closed soon unless the reporter gives more information on the issue.
