### ISSUE TITLE
[BUG] Start Simulator

### ISSUE THREAD

**Issue by kenechukwuJosiah** [SAP/e-mobility-charging-stations-simulator#1134]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Component

Simulator

### Description

I've been having trouble getting the simulator to start, even though I've been following the instructions in the README. 

Bellow is the log I received when attempting to start the simulator. 

I would appreciate any assistance you can provide.

strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionResponse#/properties/idTagInfo/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:DataTransferResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ResetResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ClearCacheResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ChangeAvailabilityResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:UnlockConnectorResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ChangeConfigurationResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:GetCompositeScheduleResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:GetCompositeScheduleResponse#/properties/chargingSchedule/properties/chargingRateUnit" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:SetChargingProfileResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ClearChargingProfileResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:RemoteStartTransactionResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:RemoteStopTransactionResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:TriggerMessageResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:DataTransferResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ReserveNowResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:CancelReservationResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:DiagnosticsStatusNotificationRequest#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:MeterValuesRequest#/properties/meterValue/items/properties/sampledValue/items/properties/context" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:MeterValuesRequest#/properties/meterValue/items/properties/sampledValue/items/properties/format" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:MeterValuesRequest#/properties/meterValue/items/properties/sampledValue/items/properties/measurand" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:MeterValuesRequest#/properties/meterValue/items/properties/sampledValue/items/properties/phase" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:MeterValuesRequest#/properties/meterValue/items/properties/sampledValue/items/properties/location" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:MeterValuesRequest#/properties/meterValue/items/properties/sampledValue/items/properties/unit" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StatusNotificationRequest#/properties/errorCode" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StatusNotificationRequest#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionRequest#/properties/reason" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionRequest#/properties/transactionData/items/properties/sampledValue/items/properties/context" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionRequest#/properties/transactionData/items/properties/sampledValue/items/properties/format" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionRequest#/properties/transactionData/items/properties/sampledValue/items/properties/measurand" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionRequest#/properties/transactionData/items/properties/sampledValue/items/properties/phase" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionRequest#/properties/transactionData/items/properties/sampledValue/items/properties/location" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionRequest#/properties/transactionData/items/properties/sampledValue/items/properties/unit" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:FirmwareStatusNotificationRequest#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ResetRequest#/properties/type" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:GetCompositeScheduleRequest#/properties/chargingRateUnit" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:SetChargingProfileRequest#/properties/csChargingProfiles/properties/chargingProfilePurpose" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:SetChargingProfileRequest#/properties/csChargingProfiles/properties/chargingProfileKind" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:SetChargingProfileRequest#/properties/csChargingProfiles/properties/recurrencyKind" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:SetChargingProfileRequest#/properties/csChargingProfiles/properties/chargingSchedule/properties/chargingRateUnit" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ClearChargingProfileRequest#/properties/chargingProfilePurpose" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ChangeAvailabilityRequest#/properties/type" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:RemoteStartTransactionRequest#/properties/chargingProfile/properties/chargingProfilePurpose" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:RemoteStartTransactionRequest#/properties/chargingProfile/properties/chargingProfileKind" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:RemoteStartTransactionRequest#/properties/chargingProfile/properties/recurrencyKind" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:RemoteStartTransactionRequest#/properties/chargingProfile/properties/chargingSchedule/properties/chargingRateUnit" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:TriggerMessageRequest#/properties/requestedMessage" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:BootNotificationResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:AuthorizeResponse#/properties/idTagInfo/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StartTransactionResponse#/properties/idTagInfo/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionResponse#/properties/idTagInfo/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:DataTransferResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ResetResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ClearCacheResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ChangeAvailabilityResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:UnlockConnectorResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ChangeConfigurationResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:GetCompositeScheduleResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:GetCompositeScheduleResponse#/properties/chargingSchedule/properties/chargingRateUnit" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:SetChargingProfileResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ClearChargingProfileResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:RemoteStartTransactionResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:RemoteStopTransactionResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:TriggerMessageResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:DataTransferResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ReserveNowResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:CancelReservationResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:DiagnosticsStatusNotificationRequest#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:MeterValuesRequest#/properties/meterValue/items/properties/sampledValue/items/properties/context" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:MeterValuesRequest#/properties/meterValue/items/properties/sampledValue/items/properties/format" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:MeterValuesRequest#/properties/meterValue/items/properties/sampledValue/items/properties/measurand" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:MeterValuesRequest#/properties/meterValue/items/properties/sampledValue/items/properties/phase" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:MeterValuesRequest#/properties/meterValue/items/properties/sampledValue/items/properties/location" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:MeterValuesRequest#/properties/meterValue/items/properties/sampledValue/items/properties/unit" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StatusNotificationRequest#/properties/errorCode" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StatusNotificationRequest#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionRequest#/properties/reason" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionRequest#/properties/transactionData/items/properties/sampledValue/items/properties/context" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionRequest#/properties/transactionData/items/properties/sampledValue/items/properties/format" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionRequest#/properties/transactionData/items/properties/sampledValue/items/properties/measurand" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionRequest#/properties/transactionData/items/properties/sampledValue/items/properties/phase" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionRequest#/properties/transactionData/items/properties/sampledValue/items/properties/location" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionRequest#/properties/transactionData/items/properties/sampledValue/items/properties/unit" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:FirmwareStatusNotificationRequest#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ResetRequest#/properties/type" (strictTypes)
Charging stations simulator 1.5.1 started with 10 configured and 2 provisioned charging station(s) from 5 charging station template(s) and 9 worker(s) concurrently running in 'workerSet' mode (1 charging station(s) per worker)
Worker set/pool information: {
  version: '1.0.1',
  type: 'set',
  worker: 'thread',
  started: true,
  size: 9,
  elementsExecuting: 9,
  elementsPerWorker: 1
}
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:GetCompositeScheduleRequest#/properties/chargingRateUnit" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:SetChargingProfileRequest#/properties/csChargingProfiles/properties/chargingProfilePurpose" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:SetChargingProfileRequest#/properties/csChargingProfiles/properties/chargingProfileKind" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:SetChargingProfileRequest#/properties/csChargingProfiles/properties/recurrencyKind" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:SetChargingProfileRequest#/properties/csChargingProfiles/properties/chargingSchedule/properties/chargingRateUnit" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ClearChargingProfileRequest#/properties/chargingProfilePurpose" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ChangeAvailabilityRequest#/properties/type" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:RemoteStartTransactionRequest#/properties/chargingProfile/properties/chargingProfilePurpose" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:RemoteStartTransactionRequest#/properties/chargingProfile/properties/chargingProfileKind" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:RemoteStartTransactionRequest#/properties/chargingProfile/properties/recurrencyKind" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:RemoteStartTransactionRequest#/properties/chargingProfile/properties/chargingSchedule/properties/chargingRateUnit" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:TriggerMessageRequest#/properties/requestedMessage" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:BootNotificationResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:AuthorizeResponse#/properties/idTagInfo/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StartTransactionResponse#/properties/idTagInfo/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionResponse#/properties/idTagInfo/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:DataTransferResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ResetResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ClearCacheResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ChangeAvailabilityResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:UnlockConnectorResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ChangeConfigurationResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:GetCompositeScheduleResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:GetCompositeScheduleResponse#/properties/chargingSchedule/properties/chargingRateUnit" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:SetChargingProfileResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ClearChargingProfileResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:RemoteStartTransactionResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:RemoteStopTransactionResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:TriggerMessageResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:DataTransferResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:ReserveNowResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:CancelReservationResponse#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:DiagnosticsStatusNotificationRequest#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:MeterValuesRequest#/properties/meterValue/items/properties/sampledValue/items/properties/context" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:MeterValuesRequest#/properties/meterValue/items/properties/sampledValue/items/properties/format" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:MeterValuesRequest#/properties/meterValue/items/properties/sampledValue/items/properties/measurand" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:MeterValuesRequest#/properties/meterValue/items/properties/sampledValue/items/properties/phase" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:MeterValuesRequest#/properties/meterValue/items/properties/sampledValue/items/properties/location" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:MeterValuesRequest#/properties/meterValue/items/properties/sampledValue/items/properties/unit" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StatusNotificationRequest#/properties/errorCode" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StatusNotificationRequest#/properties/status" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionRequest#/properties/reason" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionRequest#/properties/transactionData/items/properties/sampledValue/items/properties/context" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionRequest#/properties/transactionData/items/properties/sampledValue/items/properties/format" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionRequest#/properties/transactionData/items/properties/sampledValue/items/properties/measurand" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionRequest#/properties/transactionData/items/properties/sampledValue/items/properties/phase" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionRequest#/properties/transactionData/items/properties/sampledValue/items/properties/location" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:StopTransactionRequest#/properties/transactionData/items/properties/sampledValue/items/properties/unit" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "urn:OCPP:1.6:2019:12:FirmwareStatusNotificationRequest#/properties/status" (strictTypes)

### Version

1.6

### Node.js version

v20.7.0

### System

  System:
    OS: macOS 13.6.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 524.34 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh

**Comment by jerome-benoit** [comment]
Not a bug, support request.
