### ISSUE TITLE
[FEATURE] Community support space

### ISSUE THREAD

**Issue by jerome-benoit** [SAP/e-mobility-charging-stations-simulator#1136]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Component

Simulator

### Description

Create a space to allow community support since we do not have the bandwidth to do it. 

- [x] Discussion on GitHub
- [ ] Document that usage support is done via GitHub discussion: issue templates, README.md, ...

**Comment by AviranAbady** [comment]
just open a discord @jerome-benoit

**Comment by Vlsarro** [comment]
> just open a discord @jerome-benoit

Nah, github discussions as suggested are much better.
