### ISSUE TITLE
[BUG] Error: Cannot convert to float: 'NaN'

### ISSUE THREAD

**Issue by weiweiweizhu** [SAP/e-mobility-charging-stations-simulator#1223]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Component

Simulator

### Description

Transaction started successfully but no consumption

### Version

latest

### Node.js version

v20.16.0

### System

System:
    OS: macOS 15.1.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 83.03 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh

### Attachments

![Screenshot 2024-11-20 at 18 33 40](https://github.com/user-attachments/assets/c895b225-a517-43c9-bfe5-070a6dab5950)

**Comment by jerome-benoit** [comment]
Is the bug reproducible? If yes, please give the stacktrace (as text) with the simulator started with `pnpm start:dev`
