### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by PradeepGanapathi** [SAP/e-mobility-charging-stations-simulator#333]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

- after cloning the code I have given npm install on root directory.
- then npm start to start the server. 
- started the client side server also.
- after clicking the start simulator button on client side in console it shows the error **WebSocket connection to 'ws://localhost:8080/' failed:**

### e-mobility-charging-stations-simulator version

1.1.88

### Node.js Version

v16.17.1

### System

 OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 91.77 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh

### Expected result

Expected to start the webSocket connection and able to view the list of charging stations after clicking the start simulator.

### Actual result

Actually it shows the error like WebSocket connection to 'ws://localhost:8080/' failed:

### Attachments

<img width="1439" alt="Screenshot 2022-12-27 at 2 35 07 PM" src="https://user-images.githubusercontent.com/114913761/209764160-c091c502-1145-47e6-aafa-5def15c23d62.png">

**Comment by jerome-benoit** [comment]
You need do not have an OCPP-J server to connect to (here at ws://localhost:8080/).

robohydra in the repo can be used as WS server. But you then will have to manually do the OCPP-J message sequence on robohydra message endpoint.

**Comment by PradeepGanapathi** [comment]
<img width="1072" alt="Screenshot 2022-12-29 at 3 02 11 PM" src="https://user-images.githubusercontent.com/114913761/209932971-f5972921-2c9d-422b-9496-1eb70cbe6566.png">

but after giving npm start in root folder it shows simulator started.

**Comment by jerome-benoit** [comment]
Sorry, I confounded WebSockets server. You need to enable the UI server in the main configuration file with authentication enabled: 
 
```json
"uiServer": {
    "enabled": true,
    "type": "ws",
    "authentication": {
      "enabled": false,
      "type": "basic-auth",
      "username": "admin",
      "password": "admin"
    }
  },
```

**Comment by PradeepGanapathi** [comment]
Thanks for your kind response.
- I have changed the configuration as per your instruction.
<img width="1101" alt="Screenshot 2022-12-29 at 4 08 54 PM" src="https://user-images.githubusercontent.com/114913761/209939804-e9642014-edb7-41e5-ba3e-3d70fb89a543.png">

- I'm still getting the same error.
<img width="559" alt="Screenshot 2022-12-29 at 4 12 06 PM" src="https://user-images.githubusercontent.com/114913761/209940103-1cb63b05-ea4f-4590-ac57-2c0dd9d23376.png">

**Comment by jerome-benoit** [comment]
> <img alt="Screenshot 2022-12-29 at 4 08 54 PM" width="1101" src="https://user-images.githubusercontent.com/114913761/209939804-e9642014-edb7-41e5-ba3e-3d70fb89a543.png">

Please follow the simulator README.md and read it thoroughly: the configuration file template must be copied to config.json.

**Comment by PradeepGanapathi** [comment]
Thank you so much, it worked.
