### ISSUE TITLE
[BUG] Reboot during de firmware update

### ISSUE THREAD

**Issue by LudoSAP** [SAP/e-mobility-charging-stations-simulator#459]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

When the CS is rebooted during downloading, the CS reconnects once to say "installed" and then reconnects a second time and says "installed" again.
In the same firmware update it goes from "1.10.4" to "1.10.6", so 2 versions.
The "installing" and "downloaded" do not appear.

### e-mobility-charging-stations-simulator version

1.1.96

### Node.js Version

v16.18.0

### System

System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 110.62 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh

### Expected result

**This is the normal behaviour :**
OcppUpdateFirmware is sent to the station
StatusNotification received with connector ID'1' status Unavailable
FirmwareStatusNotification received with status Downloading
FirmwareStatusNotification received with status Downloaded
FirmwareStatusNotification received with status Installing
OcppReset is sent to the station
BootNotification received
FirmwareStatusNotification received with status InstallationFailed

### Actual result

OcppUpdateFirmware is sent to the station 
StatusNotification received with connector ID'1' status Unavailable
FirmwareStatusNotification received with status Downloading
OcppReset is sent to the station
StatusNotification received with connector ID'1' status Unavailable
BootNotification received
FirmwareStatusNotification received with status Installed 1.10.4
BootNotification received
StatusNotification received with connector ID'1' status Unavailable
StatusNotification received with connector ID'1' status Available
FirmwareStatusNotification received with status Installed 1.10.5

### Attachments

I'll let you show the full test in the wiki on the right at "Reboot during de firmware update": 
https://wiki.one.int.sap/wiki/display/EMobility/Simulator

**Comment by jerome-benoit** [comment]
Fixed in 1bf29f5
