### ISSUE TITLE
[FEATURE] Implement Vue.js web UI to pilot the simulated charging stations through the UI protocol

### ISSUE THREAD

**Issue by HazbinFaulted** [SAP/e-mobility-charging-stations-simulator#55]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

## Preparation ##

- [x] Install Vue.js in `src/ui/web` as a standalone node.js application. 
- [x] Serve that application locally with `express.static`
	- [x] add a npm script to start the local HTTP server 
	- [ ] ...

## List simulated charging stations ##

1. Send `listChargingStations` command through websocket
2. While waiting, use any mean (loading animation...) to notify user the request is being processed
3. Once response received, display it
    - [x] Design quickly the UI listing the CS 
    - [x] Implement the design   	
4. Make that list displayed by default

## Start transaction command ##

1. Send `startTransaction` command through websocket
2. While waiting, use any mean (loading animation...) to notify user the request is being processed
3. Once response received, display it

## Stop transaction command ##

1. Send `stopTransaction` command through websocket
2. While waiting, use any mean (loading animation...) to notify user the request is being processed
3. Once response received, display it

**Comment by jerome-benoit** [comment]
The Web UI has initial support for listing charging stations and start transaction. 
Support for: 
+ stopTransaction
+ startChargingStation
+ stopChargingStation
+ openConnection
+ closeConnection
is still missing

The Web UI design can also be improved.

**Comment by jerome-benoit** [comment]
Since commit https://github.com/SAP/e-mobility-charging-stations-simulator/commit/16fe3949f743c57db407cc02a5c017af4da1c7a9, all supported UI protocol commands are implemented.
