### ISSUE TITLE
[BUG] wrong number of arguments in URL

### ISSUE THREAD

**Issue by CTtest725** [SAP/e-mobility-charging-stations-simulator#663]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

For the `supervisionUrls ` in the `config.json` file, as the instruction implied, a url of the json server should be included and so I did. However the error message `Open > WS Connection ID 'OpNMq' has been rejected and closed by server due to an exception: Wrong number of arguments in URL '/OCPP16/CS-SCHNEIDER-00001'` in the ev-server terminal. I am assuming it has some connection build up across the 2 sides ( since the message pop in in the ev-server side instead of simulator side) but it couldn't quite work out.

I have tried the original url `ws://0.0.0.0:8010/OCPP16/5be7fb271014d90008992f06` that came along with the template and the same error message showed up as well. If I simply use `ws://0.0.0.0:8010/`, then I think there's simply no connection.

Sorry in advance if this is not a bug and I am messing things up. If that's the case, I still hope you can help me with this issue. Though I totally understand if it is not possible. Much appreciated! 

log file attached below:

[combined-2023-08-14.log](https://github.com/SAP/e-mobility-charging-stations-simulator/files/12333577/combined-2023-08-14.log)

**Comment by jerome-benoit** [comment]
not a bug

**Comment by CTtest725** [comment]
Do you mind telling me the solution to my problem? I totally understand if you mind but I would really appreciate your help.
