### ISSUE TITLE
[FEATURE] WS commands for qmate automated e2e tests 

### ISSUE THREAD

**Issue by bigsfr** [SAP/e-mobility-charging-stations-simulator#72]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

In automated e2e tests and regression tests context,
we would make great use of following features: 

With WS/http remote commands:
- add and start a new CS following a given template with given onboarding url.
- for given CS, set a new auth token url
- reboot CS
- start/stop charging session

**Comment by jerome-benoit** [comment]
Please add the piloting commands you need under the issue https://github.com/SAP/e-mobility-charging-stations-simulator/issues/48 (and read carefully already opened issues before creating duplicates)
