### ISSUE TITLE
[BUG] GetBaseReport returns error for mandatory featre

### ISSUE THREAD

**Issue by aidnani1** [SAP/e-mobility-charging-stations-simulator#948]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I am trying to use the simulator as a 2.0.1 charger and get an error when I try to connect to CSMS. 

Log line below. I can see that it says 'not implemented'. But given that this is a mandatory 2.0.1 requirement, and is the first message from CSMS, how do I get the simulator to work as a 2.0.1 station if the most basic requirement fails.

Incoming OCPP command 'GetBaseReport' message '[2,"fa2b8892-a9a8-42cf-8e36-7a5b148f49e7","GetBaseReport",{"requestId":754714,"reportBase":"FullInventory"}]' processing error: GetBaseReport is not implemented to handle request PDU {
  "requestId": 754714,
  "reportBase": "FullInventory"
}

### e-mobility-charging-stations-simulator version

1.2.32

### Node.js version

21.5.0

### System

  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 64.17 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh

### Expected result

The simulator should work as a 2.0.1 charging station

### Actual result

Fails

**Comment by jerome-benoit** [comment]
The README gives the support status of each OCPP commands. And that command is still not supported. PR adding support to it welcome.
