### ISSUE TITLE
[BUG]  ocpp1.6 RemoteStartTransaction reply is sent only after StatusNotification.req + Authorize.req + StartTransaction.req

### ISSUE THREAD

**Issue by Ohad31415** [SAP/e-mobility-charging-stations-simulator#959]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

`handleRequestRemoteStartTransaction` is waiting only after status-notification + authorize if needed + start-transaction to send the central-system a reply on the remote-transaction, isn't it not according the the protocol/docs?

### e-mobility-charging-stations-simulator version

1.0.1

### Node.js version

v21.5.0

### System

  System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 77.25 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh

### Expected result

The simulator replying with `RemoteStartTransaction.conf` and then manage the sequence of `StatusNotification`, `Authorize` and `StartTransaction`

**Comment by jerome-benoit** [comment]
Could you please extract the OCPP spec content that seems not respected by the code in the repo?
Are you sure about the simulator version reported in the issue?

**Comment by Ohad31415** [comment]
Thanks for the reply!
According to the docs here https://www.oasis-open.org/committees/download.php/58944/ocpp-1.6.pd -
RemoteStartTransaction is no different then other message that each request should get a reply result/error, the remote-start if accepted has effects later that it shall do+send status, authorize if needed, update and start-transaction

<img width="726" alt="Screenshot 2024-01-29 at 13 22 31" src="https://github.com/SAP/e-mobility-charging-stations-simulator/assets/47403773/a33e0c3c-68fd-43f8-b0b4-e7a824dad4e3">

**Comment by jerome-benoit** [comment]
Where exactly the code miss to follow the spec? The code behave as written, expect if a template tunable flag is changed.

**Comment by Ohad31415** [comment]
What flag is it? maybe I missed it

**Comment by jerome-benoit** [comment]
The start transaction response is checked only if `AuthorizeRemoteTxRequests` is set to `true`, which is not the behavior described in the specs.

**Comment by Ohad31415** [comment]
That's fine and following the docs completely, but why the RemoteStartTransaction reply isn't sent after the central-system request and is only sent after the start-transaction reply from central-system?  

I think that this is the right flow - 

```mermaid
sequenceDiagram
autonumber

CS->>CP: RemoteStartTransaction.req
CP-->>CS: RemoteStartTransaction.conf

CP->CS: Should authorize?
CP->CS: StatusNotification

CP->>CS: StartTransaction.req
CS-->>CP: StartTransaction.conf
```

Where currently it sends the central-system the `RemoteStartTransaction.conf` after the `StartTransaction.conf` instead of after the `RemoteStartTransaction.req`

**Comment by jerome-benoit** [comment]
The asynchronous authorization check described in the spec is: 
+ pointless
+ require some supplemental code to stop the transaction if finally the start transaction response is not accepted

I do not see the point to start the transaction if `AuthorizeRemoteTxRequests` is set to false, then check if the transaction can be started via a `startTransaction`, then conditionally stop the started transaction ... 
If I only make the code return an accepted answer without adding the `startTransaction` check and conditional `stopTransaction`. 
So I will implement a synchronous authorization check for all cases.

**Comment by jerome-benoit** [comment]
@Ohad31415: Could you please confirm or infirm that PR fix the issue by checking out its branch?

**Comment by Ohad31415** [comment]
I still doesn't reply to the `RemoteStartTransaction` first and does it after waiting for response for `StartTransaction` from central-system

**Comment by jerome-benoit** [comment]
@Ohad31415: and with the latest commit in the commit triggering a delayed start transaction?

**Comment by Ohad31415** [comment]
I still get the start-transaction before the reply on the remote-start-transaction

**Comment by jerome-benoit** [comment]
The event emission is queued in the promises queue. Hopefully the FIFO will queue it after the OCPP request promise resolving in most case.

**Comment by jerome-benoit** [comment]
> The event emission is queued in the promises queue. Hopefully the FIFO will queue it after the OCPP request handler promise resolving in most case.

The latest code in main implement a deterministic chronologically ordered 2 stages incoming request handling framework.
